TARGETNAME = FeedBack
TARGET = bin/$(TARGETNAME)

OBJS = Source/StringBox.o \
Source/MsgBox.o \
Source/ListBox.o \
Source/ComboBox.o \
Source/FileSelector.o \
Source/FingerEditor.o \
Source/Song.o \
Source/Settings.o \
Source/Player.o \
Source/OldEditor.o \
Source/Mixer.o \
Source/MidiFile.o \
Source/Menu.o \
Source/Main.o \
Source/Help.o \
Source/Game.o \
Source/GHScreen.o \
Source/FeedBack.o \
Source/Control.o \
Source/Boot.o \
Source/Gadgets/Entity.o \
Source/Gadgets/Frame.o \
Source/Gadgets/ImageProp.o \
Source/Gadgets/ModelProp.o \
Source/Gadgets/TextProp.o \
Source/Gadgets/Track.o \
Source/Screens/Download.o \
Source/Screens/Editor.o \
Source/Screens/MainMenu.o \
Source/Screens/Nationality.o \
Source/Screens/Screen.o \
Source/Tools/EventSuggestions.o \
Source/Tools/NoteScoreKeeper.o \
Source/Tools/StringEntryLogic.o

# Source/Title.o \
# Source/Gadgets/CameraProp.o \
# Source/Gadgets/Scene.o \
# Source/Tools/HashTable.o \

ifeq ($(FUJIPATH),)
FUJIPATH = ../Fuji
endif

include $(FUJIPATH)/MakeGame.inc
